[general]
email = "ammar.muhammed@geg-construction.com"

[DATABASE_URL]
DATABASE_URL = "postgresql://neondb_owner:npg_4tHf0QodJPcL@ep-little-mouse-a901ludc-pooler.gwc.azure.neon.tech/neondb?sslmode=require"
