[general]
email = "ammar.muhammed@geg-construction.com"

[DATABASE_URL]
DATABASE_URL = "postgresql://neondb_owner:npg_YkLwEqy5G7bD@ep-delicate-morning-a9ekb5nd-pooler.gwc.azure.neon.tech/neondb?sslmode=require"
